// Code generated by MockGen. DO NOT EDIT.
// Source: analytics.go
//
// Generated by this command:
//
//	mockgen -source=analytics.go -destination=analytics_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockanalyticsResponseRepository is a mock of analyticsResponseRepository interface.
type MockanalyticsResponseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockanalyticsResponseRepositoryMockRecorder
	isgomock struct{}
}

// MockanalyticsResponseRepositoryMockRecorder is the mock recorder for MockanalyticsResponseRepository.
type MockanalyticsResponseRepositoryMockRecorder struct {
	mock *MockanalyticsResponseRepository
}

// NewMockanalyticsResponseRepository creates a new mock instance.
func NewMockanalyticsResponseRepository(ctrl *gomock.Controller) *MockanalyticsResponseRepository {
	mock := &MockanalyticsResponseRepository{ctrl: ctrl}
	mock.recorder = &MockanalyticsResponseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockanalyticsResponseRepository) EXPECT() *MockanalyticsResponseRepositoryMockRecorder {
	return m.recorder
}

// CountChoicesByStudy mocks base method.
func (m *MockanalyticsResponseRepository) CountChoicesByStudy(ctx context.Context, studyID uuid.UUID) (int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountChoicesByStudy", ctx, studyID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CountChoicesByStudy indicates an expected call of CountChoicesByStudy.
func (mr *MockanalyticsResponseRepositoryMockRecorder) CountChoicesByStudy(ctx, studyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountChoicesByStudy", reflect.TypeOf((*MockanalyticsResponseRepository)(nil).CountChoicesByStudy), ctx, studyID)
}

// CountTotal mocks base method.
func (m *MockanalyticsResponseRepository) CountTotal(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotal", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotal indicates an expected call of CountTotal.
func (mr *MockanalyticsResponseRepositoryMockRecorder) CountTotal(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotal", reflect.TypeOf((*MockanalyticsResponseRepository)(nil).CountTotal), ctx)
}

// MockanalyticsRow is a mock of analyticsRow interface.
type MockanalyticsRow struct {
	ctrl     *gomock.Controller
	recorder *MockanalyticsRowMockRecorder
	isgomock struct{}
}

// MockanalyticsRowMockRecorder is the mock recorder for MockanalyticsRow.
type MockanalyticsRowMockRecorder struct {
	mock *MockanalyticsRow
}

// NewMockanalyticsRow creates a new mock instance.
func NewMockanalyticsRow(ctrl *gomock.Controller) *MockanalyticsRow {
	mock := &MockanalyticsRow{ctrl: ctrl}
	mock.recorder = &MockanalyticsRowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockanalyticsRow) EXPECT() *MockanalyticsRowMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockanalyticsRow) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockanalyticsRowMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockanalyticsRow)(nil).Scan), dest...)
}

// MockanalyticsRows is a mock of analyticsRows interface.
type MockanalyticsRows struct {
	ctrl     *gomock.Controller
	recorder *MockanalyticsRowsMockRecorder
	isgomock struct{}
}

// MockanalyticsRowsMockRecorder is the mock recorder for MockanalyticsRows.
type MockanalyticsRowsMockRecorder struct {
	mock *MockanalyticsRows
}

// NewMockanalyticsRows creates a new mock instance.
func NewMockanalyticsRows(ctrl *gomock.Controller) *MockanalyticsRows {
	mock := &MockanalyticsRows{ctrl: ctrl}
	mock.recorder = &MockanalyticsRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockanalyticsRows) EXPECT() *MockanalyticsRowsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockanalyticsRows) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockanalyticsRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockanalyticsRows)(nil).Close))
}

// Err mocks base method.
func (m *MockanalyticsRows) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockanalyticsRowsMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockanalyticsRows)(nil).Err))
}

// Next mocks base method.
func (m *MockanalyticsRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockanalyticsRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockanalyticsRows)(nil).Next))
}

// Scan mocks base method.
func (m *MockanalyticsRows) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockanalyticsRowsMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockanalyticsRows)(nil).Scan), dest...)
}

// MockanalyticsDB is a mock of analyticsDB interface.
type MockanalyticsDB struct {
	ctrl     *gomock.Controller
	recorder *MockanalyticsDBMockRecorder
	isgomock struct{}
}

// MockanalyticsDBMockRecorder is the mock recorder for MockanalyticsDB.
type MockanalyticsDBMockRecorder struct {
	mock *MockanalyticsDB
}

// NewMockanalyticsDB creates a new mock instance.
func NewMockanalyticsDB(ctrl *gomock.Controller) *MockanalyticsDB {
	mock := &MockanalyticsDB{ctrl: ctrl}
	mock.recorder = &MockanalyticsDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockanalyticsDB) EXPECT() *MockanalyticsDBMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockanalyticsDB) Query(ctx context.Context, sql string, args ...any) (analyticsRows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(analyticsRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockanalyticsDBMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockanalyticsDB)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockanalyticsDB) QueryRow(ctx context.Context, sql string, args ...any) analyticsRow {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(analyticsRow)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockanalyticsDBMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockanalyticsDB)(nil).QueryRow), varargs...)
}
