// Code generated by MockGen. DO NOT EDIT.
// Source: asset.go
//
// Generated by this command:
//
//	mockgen -source=asset.go -destination=asset_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	model "comp-video-service/backend/internal/model"
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockassetVideoRepository is a mock of assetVideoRepository interface.
type MockassetVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockassetVideoRepositoryMockRecorder
	isgomock struct{}
}

// MockassetVideoRepositoryMockRecorder is the mock recorder for MockassetVideoRepository.
type MockassetVideoRepositoryMockRecorder struct {
	mock *MockassetVideoRepository
}

// NewMockassetVideoRepository creates a new mock instance.
func NewMockassetVideoRepository(ctrl *gomock.Controller) *MockassetVideoRepository {
	mock := &MockassetVideoRepository{ctrl: ctrl}
	mock.recorder = &MockassetVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassetVideoRepository) EXPECT() *MockassetVideoRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockassetVideoRepository) Create(ctx context.Context, m *model.Video) (*model.Video, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockassetVideoRepositoryMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockassetVideoRepository)(nil).Create), ctx, m)
}

// MockassetStorage is a mock of assetStorage interface.
type MockassetStorage struct {
	ctrl     *gomock.Controller
	recorder *MockassetStorageMockRecorder
	isgomock struct{}
}

// MockassetStorageMockRecorder is the mock recorder for MockassetStorage.
type MockassetStorageMockRecorder struct {
	mock *MockassetStorage
}

// NewMockassetStorage creates a new mock instance.
func NewMockassetStorage(ctrl *gomock.Controller) *MockassetStorage {
	mock := &MockassetStorage{ctrl: ctrl}
	mock.recorder = &MockassetStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassetStorage) EXPECT() *MockassetStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockassetStorage) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockassetStorageMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockassetStorage)(nil).Delete), ctx, key)
}

// Upload mocks base method.
func (m *MockassetStorage) Upload(ctx context.Context, key, contentType string, body io.Reader, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, contentType, body, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockassetStorageMockRecorder) Upload(ctx, key, contentType, body, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockassetStorage)(nil).Upload), ctx, key, contentType, body, size)
}
