// Code generated by MockGen. DO NOT EDIT.
// Source: assignment.go
//
// Generated by this command:
//
//	mockgen -source=assignment.go -destination=assignment_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	model "comp-video-service/backend/internal/model"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockassignmentSourceItemRepository is a mock of assignmentSourceItemRepository interface.
type MockassignmentSourceItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockassignmentSourceItemRepositoryMockRecorder
	isgomock struct{}
}

// MockassignmentSourceItemRepositoryMockRecorder is the mock recorder for MockassignmentSourceItemRepository.
type MockassignmentSourceItemRepositoryMockRecorder struct {
	mock *MockassignmentSourceItemRepository
}

// NewMockassignmentSourceItemRepository creates a new mock instance.
func NewMockassignmentSourceItemRepository(ctrl *gomock.Controller) *MockassignmentSourceItemRepository {
	mock := &MockassignmentSourceItemRepository{ctrl: ctrl}
	mock.recorder = &MockassignmentSourceItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassignmentSourceItemRepository) EXPECT() *MockassignmentSourceItemRepositoryMockRecorder {
	return m.recorder
}

// ListByStudy mocks base method.
func (m *MockassignmentSourceItemRepository) ListByStudy(ctx context.Context, studyID uuid.UUID) ([]*model.SourceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStudy", ctx, studyID)
	ret0, _ := ret[0].([]*model.SourceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStudy indicates an expected call of ListByStudy.
func (mr *MockassignmentSourceItemRepositoryMockRecorder) ListByStudy(ctx, studyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStudy", reflect.TypeOf((*MockassignmentSourceItemRepository)(nil).ListByStudy), ctx, studyID)
}

// ResponseCountsByStudy mocks base method.
func (m *MockassignmentSourceItemRepository) ResponseCountsByStudy(ctx context.Context, studyID uuid.UUID) (map[uuid.UUID]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseCountsByStudy", ctx, studyID)
	ret0, _ := ret[0].(map[uuid.UUID]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResponseCountsByStudy indicates an expected call of ResponseCountsByStudy.
func (mr *MockassignmentSourceItemRepositoryMockRecorder) ResponseCountsByStudy(ctx, studyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseCountsByStudy", reflect.TypeOf((*MockassignmentSourceItemRepository)(nil).ResponseCountsByStudy), ctx, studyID)
}

// MockassignmentGroupRepository is a mock of assignmentGroupRepository interface.
type MockassignmentGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockassignmentGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockassignmentGroupRepositoryMockRecorder is the mock recorder for MockassignmentGroupRepository.
type MockassignmentGroupRepositoryMockRecorder struct {
	mock *MockassignmentGroupRepository
}

// NewMockassignmentGroupRepository creates a new mock instance.
func NewMockassignmentGroupRepository(ctrl *gomock.Controller) *MockassignmentGroupRepository {
	mock := &MockassignmentGroupRepository{ctrl: ctrl}
	mock.recorder = &MockassignmentGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassignmentGroupRepository) EXPECT() *MockassignmentGroupRepositoryMockRecorder {
	return m.recorder
}

// ListByStudy mocks base method.
func (m *MockassignmentGroupRepository) ListByStudy(ctx context.Context, studyID uuid.UUID) ([]*model.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStudy", ctx, studyID)
	ret0, _ := ret[0].([]*model.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStudy indicates an expected call of ListByStudy.
func (mr *MockassignmentGroupRepositoryMockRecorder) ListByStudy(ctx, studyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStudy", reflect.TypeOf((*MockassignmentGroupRepository)(nil).ListByStudy), ctx, studyID)
}

// MockassignmentVideoRepository is a mock of assignmentVideoRepository interface.
type MockassignmentVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockassignmentVideoRepositoryMockRecorder
	isgomock struct{}
}

// MockassignmentVideoRepositoryMockRecorder is the mock recorder for MockassignmentVideoRepository.
type MockassignmentVideoRepositoryMockRecorder struct {
	mock *MockassignmentVideoRepository
}

// NewMockassignmentVideoRepository creates a new mock instance.
func NewMockassignmentVideoRepository(ctrl *gomock.Controller) *MockassignmentVideoRepository {
	mock := &MockassignmentVideoRepository{ctrl: ctrl}
	mock.recorder = &MockassignmentVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassignmentVideoRepository) EXPECT() *MockassignmentVideoRepositoryMockRecorder {
	return m.recorder
}

// ListBySourceItem mocks base method.
func (m *MockassignmentVideoRepository) ListBySourceItem(ctx context.Context, sourceItemID uuid.UUID) ([]*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySourceItem", ctx, sourceItemID)
	ret0, _ := ret[0].([]*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySourceItem indicates an expected call of ListBySourceItem.
func (mr *MockassignmentVideoRepositoryMockRecorder) ListBySourceItem(ctx, sourceItemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySourceItem", reflect.TypeOf((*MockassignmentVideoRepository)(nil).ListBySourceItem), ctx, sourceItemID)
}

// MockassignmentPairRepository is a mock of assignmentPairRepository interface.
type MockassignmentPairRepository struct {
	ctrl     *gomock.Controller
	recorder *MockassignmentPairRepositoryMockRecorder
	isgomock struct{}
}

// MockassignmentPairRepositoryMockRecorder is the mock recorder for MockassignmentPairRepository.
type MockassignmentPairRepositoryMockRecorder struct {
	mock *MockassignmentPairRepository
}

// NewMockassignmentPairRepository creates a new mock instance.
func NewMockassignmentPairRepository(ctrl *gomock.Controller) *MockassignmentPairRepository {
	mock := &MockassignmentPairRepository{ctrl: ctrl}
	mock.recorder = &MockassignmentPairRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassignmentPairRepository) EXPECT() *MockassignmentPairRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockassignmentPairRepository) Create(ctx context.Context, pp *model.PairPresentation) (*model.PairPresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pp)
	ret0, _ := ret[0].(*model.PairPresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockassignmentPairRepositoryMockRecorder) Create(ctx, pp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockassignmentPairRepository)(nil).Create), ctx, pp)
}
