// Code generated by MockGen. DO NOT EDIT.
// Source: export.go
//
// Generated by this command:
//
//	mockgen -source=export.go -destination=export_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockexportRows is a mock of exportRows interface.
type MockexportRows struct {
	ctrl     *gomock.Controller
	recorder *MockexportRowsMockRecorder
	isgomock struct{}
}

// MockexportRowsMockRecorder is the mock recorder for MockexportRows.
type MockexportRowsMockRecorder struct {
	mock *MockexportRows
}

// NewMockexportRows creates a new mock instance.
func NewMockexportRows(ctrl *gomock.Controller) *MockexportRows {
	mock := &MockexportRows{ctrl: ctrl}
	mock.recorder = &MockexportRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexportRows) EXPECT() *MockexportRowsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockexportRows) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockexportRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockexportRows)(nil).Close))
}

// Err mocks base method.
func (m *MockexportRows) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockexportRowsMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockexportRows)(nil).Err))
}

// Next mocks base method.
func (m *MockexportRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockexportRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockexportRows)(nil).Next))
}

// Scan mocks base method.
func (m *MockexportRows) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockexportRowsMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockexportRows)(nil).Scan), dest...)
}

// MockexportDB is a mock of exportDB interface.
type MockexportDB struct {
	ctrl     *gomock.Controller
	recorder *MockexportDBMockRecorder
	isgomock struct{}
}

// MockexportDBMockRecorder is the mock recorder for MockexportDB.
type MockexportDBMockRecorder struct {
	mock *MockexportDB
}

// NewMockexportDB creates a new mock instance.
func NewMockexportDB(ctrl *gomock.Controller) *MockexportDB {
	mock := &MockexportDB{ctrl: ctrl}
	mock.recorder = &MockexportDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexportDB) EXPECT() *MockexportDBMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockexportDB) Query(ctx context.Context, sql string, args ...any) (exportRows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(exportRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockexportDBMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockexportDB)(nil).Query), varargs...)
}
