// Code generated by MockGen. DO NOT EDIT.
// Source: qc.go
//
// Generated by this command:
//
//	mockgen -source=qc.go -destination=qc_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	model "comp-video-service/backend/internal/model"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockqcResponseRepository is a mock of qcResponseRepository interface.
type MockqcResponseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockqcResponseRepositoryMockRecorder
	isgomock struct{}
}

// MockqcResponseRepositoryMockRecorder is the mock recorder for MockqcResponseRepository.
type MockqcResponseRepositoryMockRecorder struct {
	mock *MockqcResponseRepository
}

// NewMockqcResponseRepository creates a new mock instance.
func NewMockqcResponseRepository(ctrl *gomock.Controller) *MockqcResponseRepository {
	mock := &MockqcResponseRepository{ctrl: ctrl}
	mock.recorder = &MockqcResponseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockqcResponseRepository) EXPECT() *MockqcResponseRepositoryMockRecorder {
	return m.recorder
}

// AttentionCheckStats mocks base method.
func (m *MockqcResponseRepository) AttentionCheckStats(ctx context.Context, participantID uuid.UUID) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttentionCheckStats", ctx, participantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AttentionCheckStats indicates an expected call of AttentionCheckStats.
func (mr *MockqcResponseRepositoryMockRecorder) AttentionCheckStats(ctx, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttentionCheckStats", reflect.TypeOf((*MockqcResponseRepository)(nil).AttentionCheckStats), ctx, participantID)
}

// CountAttentionCheckFailures mocks base method.
func (m *MockqcResponseRepository) CountAttentionCheckFailures(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAttentionCheckFailures", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAttentionCheckFailures indicates an expected call of CountAttentionCheckFailures.
func (mr *MockqcResponseRepositoryMockRecorder) CountAttentionCheckFailures(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAttentionCheckFailures", reflect.TypeOf((*MockqcResponseRepository)(nil).CountAttentionCheckFailures), ctx)
}

// CountByParticipant mocks base method.
func (m *MockqcResponseRepository) CountByParticipant(ctx context.Context, participantID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByParticipant", ctx, participantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByParticipant indicates an expected call of CountByParticipant.
func (mr *MockqcResponseRepositoryMockRecorder) CountByParticipant(ctx, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByParticipant", reflect.TypeOf((*MockqcResponseRepository)(nil).CountByParticipant), ctx, participantID)
}

// CountFastByParticipant mocks base method.
func (m *MockqcResponseRepository) CountFastByParticipant(ctx context.Context, participantID uuid.UUID, thresholdMS int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFastByParticipant", ctx, participantID, thresholdMS)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFastByParticipant indicates an expected call of CountFastByParticipant.
func (mr *MockqcResponseRepositoryMockRecorder) CountFastByParticipant(ctx, participantID, thresholdMS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFastByParticipant", reflect.TypeOf((*MockqcResponseRepository)(nil).CountFastByParticipant), ctx, participantID, thresholdMS)
}

// CountFastResponses mocks base method.
func (m *MockqcResponseRepository) CountFastResponses(ctx context.Context, thresholdMS int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFastResponses", ctx, thresholdMS)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFastResponses indicates an expected call of CountFastResponses.
func (mr *MockqcResponseRepositoryMockRecorder) CountFastResponses(ctx, thresholdMS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFastResponses", reflect.TypeOf((*MockqcResponseRepository)(nil).CountFastResponses), ctx, thresholdMS)
}

// CountTotal mocks base method.
func (m *MockqcResponseRepository) CountTotal(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotal", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotal indicates an expected call of CountTotal.
func (mr *MockqcResponseRepositoryMockRecorder) CountTotal(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotal", reflect.TypeOf((*MockqcResponseRepository)(nil).CountTotal), ctx)
}

// StraightLiningParticipants mocks base method.
func (m *MockqcResponseRepository) StraightLiningParticipants(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StraightLiningParticipants", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StraightLiningParticipants indicates an expected call of StraightLiningParticipants.
func (mr *MockqcResponseRepositoryMockRecorder) StraightLiningParticipants(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StraightLiningParticipants", reflect.TypeOf((*MockqcResponseRepository)(nil).StraightLiningParticipants), ctx)
}

// MockqcParticipantRepository is a mock of qcParticipantRepository interface.
type MockqcParticipantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockqcParticipantRepositoryMockRecorder
	isgomock struct{}
}

// MockqcParticipantRepositoryMockRecorder is the mock recorder for MockqcParticipantRepository.
type MockqcParticipantRepositoryMockRecorder struct {
	mock *MockqcParticipantRepository
}

// NewMockqcParticipantRepository creates a new mock instance.
func NewMockqcParticipantRepository(ctrl *gomock.Controller) *MockqcParticipantRepository {
	mock := &MockqcParticipantRepository{ctrl: ctrl}
	mock.recorder = &MockqcParticipantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockqcParticipantRepository) EXPECT() *MockqcParticipantRepositoryMockRecorder {
	return m.recorder
}

// CountByQualityFlag mocks base method.
func (m *MockqcParticipantRepository) CountByQualityFlag(ctx context.Context, flag string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByQualityFlag", ctx, flag)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByQualityFlag indicates an expected call of CountByQualityFlag.
func (mr *MockqcParticipantRepositoryMockRecorder) CountByQualityFlag(ctx, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByQualityFlag", reflect.TypeOf((*MockqcParticipantRepository)(nil).CountByQualityFlag), ctx, flag)
}

// FlaggedParticipants mocks base method.
func (m *MockqcParticipantRepository) FlaggedParticipants(ctx context.Context) ([]*model.FlaggedParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlaggedParticipants", ctx)
	ret0, _ := ret[0].([]*model.FlaggedParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FlaggedParticipants indicates an expected call of FlaggedParticipants.
func (mr *MockqcParticipantRepositoryMockRecorder) FlaggedParticipants(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlaggedParticipants", reflect.TypeOf((*MockqcParticipantRepository)(nil).FlaggedParticipants), ctx)
}

// UpdateQualityFlag mocks base method.
func (m *MockqcParticipantRepository) UpdateQualityFlag(ctx context.Context, participantID uuid.UUID, qualityFlag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQualityFlag", ctx, participantID, qualityFlag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQualityFlag indicates an expected call of UpdateQualityFlag.
func (mr *MockqcParticipantRepositoryMockRecorder) UpdateQualityFlag(ctx, participantID, qualityFlag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQualityFlag", reflect.TypeOf((*MockqcParticipantRepository)(nil).UpdateQualityFlag), ctx, participantID, qualityFlag)
}
