// Code generated by MockGen. DO NOT EDIT.
// Source: session.go
//
// Generated by this command:
//
//	mockgen -source=session.go -destination=session_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	model "comp-video-service/backend/internal/model"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MocksessionStudyRepository is a mock of sessionStudyRepository interface.
type MocksessionStudyRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksessionStudyRepositoryMockRecorder
	isgomock struct{}
}

// MocksessionStudyRepositoryMockRecorder is the mock recorder for MocksessionStudyRepository.
type MocksessionStudyRepositoryMockRecorder struct {
	mock *MocksessionStudyRepository
}

// NewMocksessionStudyRepository creates a new mock instance.
func NewMocksessionStudyRepository(ctrl *gomock.Controller) *MocksessionStudyRepository {
	mock := &MocksessionStudyRepository{ctrl: ctrl}
	mock.recorder = &MocksessionStudyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionStudyRepository) EXPECT() *MocksessionStudyRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocksessionStudyRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Study, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocksessionStudyRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocksessionStudyRepository)(nil).GetByID), ctx, id)
}

// MocksessionParticipantRepository is a mock of sessionParticipantRepository interface.
type MocksessionParticipantRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksessionParticipantRepositoryMockRecorder
	isgomock struct{}
}

// MocksessionParticipantRepositoryMockRecorder is the mock recorder for MocksessionParticipantRepository.
type MocksessionParticipantRepositoryMockRecorder struct {
	mock *MocksessionParticipantRepository
}

// NewMocksessionParticipantRepository creates a new mock instance.
func NewMocksessionParticipantRepository(ctrl *gomock.Controller) *MocksessionParticipantRepository {
	mock := &MocksessionParticipantRepository{ctrl: ctrl}
	mock.recorder = &MocksessionParticipantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionParticipantRepository) EXPECT() *MocksessionParticipantRepositoryMockRecorder {
	return m.recorder
}

// CompleteByToken mocks base method.
func (m *MocksessionParticipantRepository) CompleteByToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteByToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteByToken indicates an expected call of CompleteByToken.
func (mr *MocksessionParticipantRepositoryMockRecorder) CompleteByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteByToken", reflect.TypeOf((*MocksessionParticipantRepository)(nil).CompleteByToken), ctx, token)
}

// Create mocks base method.
func (m *MocksessionParticipantRepository) Create(ctx context.Context, p *model.Participant) (*model.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(*model.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocksessionParticipantRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocksessionParticipantRepository)(nil).Create), ctx, p)
}

// GetByToken mocks base method.
func (m *MocksessionParticipantRepository) GetByToken(ctx context.Context, token string) (*model.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*model.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MocksessionParticipantRepositoryMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MocksessionParticipantRepository)(nil).GetByToken), ctx, token)
}

// MocksessionPairRepository is a mock of sessionPairRepository interface.
type MocksessionPairRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksessionPairRepositoryMockRecorder
	isgomock struct{}
}

// MocksessionPairRepositoryMockRecorder is the mock recorder for MocksessionPairRepository.
type MocksessionPairRepositoryMockRecorder struct {
	mock *MocksessionPairRepository
}

// NewMocksessionPairRepository creates a new mock instance.
func NewMocksessionPairRepository(ctrl *gomock.Controller) *MocksessionPairRepository {
	mock := &MocksessionPairRepository{ctrl: ctrl}
	mock.recorder = &MocksessionPairRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionPairRepository) EXPECT() *MocksessionPairRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocksessionPairRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.PairPresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.PairPresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocksessionPairRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocksessionPairRepository)(nil).GetByID), ctx, id)
}

// GetNextPendingByToken mocks base method.
func (m *MocksessionPairRepository) GetNextPendingByToken(ctx context.Context, sessionToken string) (*model.PairPresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextPendingByToken", ctx, sessionToken)
	ret0, _ := ret[0].(*model.PairPresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextPendingByToken indicates an expected call of GetNextPendingByToken.
func (mr *MocksessionPairRepositoryMockRecorder) GetNextPendingByToken(ctx, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextPendingByToken", reflect.TypeOf((*MocksessionPairRepository)(nil).GetNextPendingByToken), ctx, sessionToken)
}

// MocksessionVideoRepository is a mock of sessionVideoRepository interface.
type MocksessionVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksessionVideoRepositoryMockRecorder
	isgomock struct{}
}

// MocksessionVideoRepositoryMockRecorder is the mock recorder for MocksessionVideoRepository.
type MocksessionVideoRepositoryMockRecorder struct {
	mock *MocksessionVideoRepository
}

// NewMocksessionVideoRepository creates a new mock instance.
func NewMocksessionVideoRepository(ctrl *gomock.Controller) *MocksessionVideoRepository {
	mock := &MocksessionVideoRepository{ctrl: ctrl}
	mock.recorder = &MocksessionVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionVideoRepository) EXPECT() *MocksessionVideoRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocksessionVideoRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocksessionVideoRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocksessionVideoRepository)(nil).GetByID), ctx, id)
}

// MocksessionResponseRepository is a mock of sessionResponseRepository interface.
type MocksessionResponseRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksessionResponseRepositoryMockRecorder
	isgomock struct{}
}

// MocksessionResponseRepositoryMockRecorder is the mock recorder for MocksessionResponseRepository.
type MocksessionResponseRepositoryMockRecorder struct {
	mock *MocksessionResponseRepository
}

// NewMocksessionResponseRepository creates a new mock instance.
func NewMocksessionResponseRepository(ctrl *gomock.Controller) *MocksessionResponseRepository {
	mock := &MocksessionResponseRepository{ctrl: ctrl}
	mock.recorder = &MocksessionResponseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionResponseRepository) EXPECT() *MocksessionResponseRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocksessionResponseRepository) Create(ctx context.Context, resp *model.Response) (*model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resp)
	ret0, _ := ret[0].(*model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocksessionResponseRepositoryMockRecorder) Create(ctx, resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocksessionResponseRepository)(nil).Create), ctx, resp)
}

// MocksessionAssignmentService is a mock of sessionAssignmentService interface.
type MocksessionAssignmentService struct {
	ctrl     *gomock.Controller
	recorder *MocksessionAssignmentServiceMockRecorder
	isgomock struct{}
}

// MocksessionAssignmentServiceMockRecorder is the mock recorder for MocksessionAssignmentService.
type MocksessionAssignmentServiceMockRecorder struct {
	mock *MocksessionAssignmentService
}

// NewMocksessionAssignmentService creates a new mock instance.
func NewMocksessionAssignmentService(ctrl *gomock.Controller) *MocksessionAssignmentService {
	mock := &MocksessionAssignmentService{ctrl: ctrl}
	mock.recorder = &MocksessionAssignmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionAssignmentService) EXPECT() *MocksessionAssignmentServiceMockRecorder {
	return m.recorder
}

// AssignForParticipant mocks base method.
func (m *MocksessionAssignmentService) AssignForParticipant(ctx context.Context, participantID, studyID uuid.UUID, maxTasks int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignForParticipant", ctx, participantID, studyID, maxTasks)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignForParticipant indicates an expected call of AssignForParticipant.
func (mr *MocksessionAssignmentServiceMockRecorder) AssignForParticipant(ctx, participantID, studyID, maxTasks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignForParticipant", reflect.TypeOf((*MocksessionAssignmentService)(nil).AssignForParticipant), ctx, participantID, studyID, maxTasks)
}

// MocksessionQCService is a mock of sessionQCService interface.
type MocksessionQCService struct {
	ctrl     *gomock.Controller
	recorder *MocksessionQCServiceMockRecorder
	isgomock struct{}
}

// MocksessionQCServiceMockRecorder is the mock recorder for MocksessionQCService.
type MocksessionQCServiceMockRecorder struct {
	mock *MocksessionQCService
}

// NewMocksessionQCService creates a new mock instance.
func NewMocksessionQCService(ctrl *gomock.Controller) *MocksessionQCService {
	mock := &MocksessionQCService{ctrl: ctrl}
	mock.recorder = &MocksessionQCServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionQCService) EXPECT() *MocksessionQCServiceMockRecorder {
	return m.recorder
}

// EvaluateParticipantFinalFlag mocks base method.
func (m *MocksessionQCService) EvaluateParticipantFinalFlag(ctx context.Context, participantID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateParticipantFinalFlag", ctx, participantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EvaluateParticipantFinalFlag indicates an expected call of EvaluateParticipantFinalFlag.
func (mr *MocksessionQCServiceMockRecorder) EvaluateParticipantFinalFlag(ctx, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateParticipantFinalFlag", reflect.TypeOf((*MocksessionQCService)(nil).EvaluateParticipantFinalFlag), ctx, participantID)
}

// UpdateParticipantFlag mocks base method.
func (m *MocksessionQCService) UpdateParticipantFlag(ctx context.Context, participantID uuid.UUID, responseTimeMS *int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipantFlag", ctx, participantID, responseTimeMS)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateParticipantFlag indicates an expected call of UpdateParticipantFlag.
func (mr *MocksessionQCServiceMockRecorder) UpdateParticipantFlag(ctx, participantID, responseTimeMS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipantFlag", reflect.TypeOf((*MocksessionQCService)(nil).UpdateParticipantFlag), ctx, participantID, responseTimeMS)
}

// MocksessionStorage is a mock of sessionStorage interface.
type MocksessionStorage struct {
	ctrl     *gomock.Controller
	recorder *MocksessionStorageMockRecorder
	isgomock struct{}
}

// MocksessionStorageMockRecorder is the mock recorder for MocksessionStorage.
type MocksessionStorageMockRecorder struct {
	mock *MocksessionStorage
}

// NewMocksessionStorage creates a new mock instance.
func NewMocksessionStorage(ctrl *gomock.Controller) *MocksessionStorage {
	mock := &MocksessionStorage{ctrl: ctrl}
	mock.recorder = &MocksessionStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionStorage) EXPECT() *MocksessionStorageMockRecorder {
	return m.recorder
}

// PresignedURL mocks base method.
func (m *MocksessionStorage) PresignedURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedURL", ctx, key, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedURL indicates an expected call of PresignedURL.
func (mr *MocksessionStorageMockRecorder) PresignedURL(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedURL", reflect.TypeOf((*MocksessionStorage)(nil).PresignedURL), ctx, key, ttl)
}
