// Code generated by MockGen. DO NOT EDIT.
// Source: study.go
//
// Generated by this command:
//
//	mockgen -source=study.go -destination=study_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	model "comp-video-service/backend/internal/model"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockstudyRepository is a mock of studyRepository interface.
type MockstudyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockstudyRepositoryMockRecorder
	isgomock struct{}
}

// MockstudyRepositoryMockRecorder is the mock recorder for MockstudyRepository.
type MockstudyRepositoryMockRecorder struct {
	mock *MockstudyRepository
}

// NewMockstudyRepository creates a new mock instance.
func NewMockstudyRepository(ctrl *gomock.Controller) *MockstudyRepository {
	mock := &MockstudyRepository{ctrl: ctrl}
	mock.recorder = &MockstudyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstudyRepository) EXPECT() *MockstudyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockstudyRepository) Create(ctx context.Context, req *model.CreateStudyRequest) (*model.Study, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*model.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockstudyRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockstudyRepository)(nil).Create), ctx, req)
}

// List mocks base method.
func (m *MockstudyRepository) List(ctx context.Context) ([]*model.Study, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*model.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockstudyRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockstudyRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockstudyRepository) Update(ctx context.Context, id uuid.UUID, req *model.UpdateStudyRequest) (*model.Study, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*model.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockstudyRepositoryMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockstudyRepository)(nil).Update), ctx, id, req)
}

// UpdateStatus mocks base method.
func (m *MockstudyRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) (*model.Study, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(*model.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockstudyRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockstudyRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockgroupRepository is a mock of groupRepository interface.
type MockgroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockgroupRepositoryMockRecorder
	isgomock struct{}
}

// MockgroupRepositoryMockRecorder is the mock recorder for MockgroupRepository.
type MockgroupRepositoryMockRecorder struct {
	mock *MockgroupRepository
}

// NewMockgroupRepository creates a new mock instance.
func NewMockgroupRepository(ctrl *gomock.Controller) *MockgroupRepository {
	mock := &MockgroupRepository{ctrl: ctrl}
	mock.recorder = &MockgroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupRepository) EXPECT() *MockgroupRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockgroupRepository) Create(ctx context.Context, studyID uuid.UUID, req *model.CreateGroupRequest) (*model.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, studyID, req)
	ret0, _ := ret[0].(*model.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockgroupRepositoryMockRecorder) Create(ctx, studyID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockgroupRepository)(nil).Create), ctx, studyID, req)
}

// ListByStudy mocks base method.
func (m *MockgroupRepository) ListByStudy(ctx context.Context, studyID uuid.UUID) ([]*model.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStudy", ctx, studyID)
	ret0, _ := ret[0].([]*model.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStudy indicates an expected call of ListByStudy.
func (mr *MockgroupRepositoryMockRecorder) ListByStudy(ctx, studyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStudy", reflect.TypeOf((*MockgroupRepository)(nil).ListByStudy), ctx, studyID)
}

// MocksourceItemRepository is a mock of sourceItemRepository interface.
type MocksourceItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksourceItemRepositoryMockRecorder
	isgomock struct{}
}

// MocksourceItemRepositoryMockRecorder is the mock recorder for MocksourceItemRepository.
type MocksourceItemRepositoryMockRecorder struct {
	mock *MocksourceItemRepository
}

// NewMocksourceItemRepository creates a new mock instance.
func NewMocksourceItemRepository(ctrl *gomock.Controller) *MocksourceItemRepository {
	mock := &MocksourceItemRepository{ctrl: ctrl}
	mock.recorder = &MocksourceItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksourceItemRepository) EXPECT() *MocksourceItemRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocksourceItemRepository) Create(ctx context.Context, item *model.SourceItem) (*model.SourceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item)
	ret0, _ := ret[0].(*model.SourceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocksourceItemRepositoryMockRecorder) Create(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocksourceItemRepository)(nil).Create), ctx, item)
}

// Delete mocks base method.
func (m *MocksourceItemRepository) Delete(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MocksourceItemRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocksourceItemRepository)(nil).Delete), ctx, id)
}

// ListWithFilters mocks base method.
func (m *MocksourceItemRepository) ListWithFilters(ctx context.Context, studyID, groupID *uuid.UUID) ([]*model.SourceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithFilters", ctx, studyID, groupID)
	ret0, _ := ret[0].([]*model.SourceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithFilters indicates an expected call of ListWithFilters.
func (mr *MocksourceItemRepositoryMockRecorder) ListWithFilters(ctx, studyID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithFilters", reflect.TypeOf((*MocksourceItemRepository)(nil).ListWithFilters), ctx, studyID, groupID)
}

// MockstudyVideoRepository is a mock of studyVideoRepository interface.
type MockstudyVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockstudyVideoRepositoryMockRecorder
	isgomock struct{}
}

// MockstudyVideoRepositoryMockRecorder is the mock recorder for MockstudyVideoRepository.
type MockstudyVideoRepositoryMockRecorder struct {
	mock *MockstudyVideoRepository
}

// NewMockstudyVideoRepository creates a new mock instance.
func NewMockstudyVideoRepository(ctrl *gomock.Controller) *MockstudyVideoRepository {
	mock := &MockstudyVideoRepository{ctrl: ctrl}
	mock.recorder = &MockstudyVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstudyVideoRepository) EXPECT() *MockstudyVideoRepositoryMockRecorder {
	return m.recorder
}

// Link mocks base method.
func (m *MockstudyVideoRepository) Link(ctx context.Context, videoID, sourceItemID uuid.UUID, methodType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Link", ctx, videoID, sourceItemID, methodType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Link indicates an expected call of Link.
func (mr *MockstudyVideoRepositoryMockRecorder) Link(ctx, videoID, sourceItemID, methodType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Link", reflect.TypeOf((*MockstudyVideoRepository)(nil).Link), ctx, videoID, sourceItemID, methodType)
}

// LinkOrCreate mocks base method.
func (m *MockstudyVideoRepository) LinkOrCreate(ctx context.Context, v *model.Video) (*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkOrCreate", ctx, v)
	ret0, _ := ret[0].(*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkOrCreate indicates an expected call of LinkOrCreate.
func (mr *MockstudyVideoRepositoryMockRecorder) LinkOrCreate(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkOrCreate", reflect.TypeOf((*MockstudyVideoRepository)(nil).LinkOrCreate), ctx, v)
}

// ListAll mocks base method.
func (m *MockstudyVideoRepository) ListAll(ctx context.Context) ([]*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockstudyVideoRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockstudyVideoRepository)(nil).ListAll), ctx)
}

// ListFree mocks base method.
func (m *MockstudyVideoRepository) ListFree(ctx context.Context) ([]*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFree", ctx)
	ret0, _ := ret[0].([]*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFree indicates an expected call of ListFree.
func (mr *MockstudyVideoRepositoryMockRecorder) ListFree(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFree", reflect.TypeOf((*MockstudyVideoRepository)(nil).ListFree), ctx)
}

// ListPaged mocks base method.
func (m *MockstudyVideoRepository) ListPaged(ctx context.Context, page, perPage int) ([]*model.Video, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaged", ctx, page, perPage)
	ret0, _ := ret[0].([]*model.Video)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPaged indicates an expected call of ListPaged.
func (mr *MockstudyVideoRepositoryMockRecorder) ListPaged(ctx, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaged", reflect.TypeOf((*MockstudyVideoRepository)(nil).ListPaged), ctx, page, perPage)
}
