// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/analytics/overview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get analytics overview",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.AnalyticsOverview"
                        }
                    }
                }
            }
        },
        "/admin/analytics/qc": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get QC report",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.QCReport"
                        }
                    }
                }
            }
        },
        "/admin/analytics/study/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get per-study analytics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Study ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.StudyAnalytics"
                        }
                    }
                }
            }
        },
        "/admin/assets/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Upload a video asset",
                "parameters": [
                    {
                        "type": "file",
                        "description": "MP4 video file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "baseline or candidate",
                        "name": "method_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source item UUID to link",
                        "name": "source_item_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Video title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Video description",
                        "name": "description",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Video"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/export/csv": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Export responses as CSV",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/export/json": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Export responses as JSON",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Admin login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/source-items": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List source items (pairs)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by study UUID",
                        "name": "study_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by group UUID",
                        "name": "group_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/studies": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all studies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create a new study",
                "parameters": [
                    {
                        "description": "Study data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateStudyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Study"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/studies/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update study status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Study ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateStudyStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Study"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/studies/{id}/groups": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List groups for a study",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Study ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create a group within a study",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Study ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Group data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Group"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/studies/{id}/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "CSRFToken": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Import source items from CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Study ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "CSV file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/session/start": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Start participant session",
                "parameters": [
                    {
                        "description": "Session data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StartSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.SessionStartResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/session/{token}/complete": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Complete participant session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.SessionCompleteResult"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/session/{token}/next-task": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Get next task for session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TaskPayload"
                        }
                    },
                    "204": {
                        "description": "No more tasks"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task/{id}/event": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "Log interaction event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pair presentation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task/{id}/response": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "Submit response for a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pair presentation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Response data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TaskResponseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Admin": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.CreateGroupRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "target_votes_per_pair": {
                    "type": "integer"
                }
            }
        },
        "model.CreateStudyRequest": {
            "type": "object",
            "required": [
                "effect_type",
                "name"
            ],
            "properties": {
                "confidence_enabled": {
                    "type": "boolean"
                },
                "effect_type": {
                    "type": "string"
                },
                "instructions_text": {
                    "type": "string"
                },
                "max_tasks_per_participant": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "reasons_enabled": {
                    "type": "boolean"
                },
                "tie_option_enabled": {
                    "type": "boolean"
                }
            }
        },
        "model.Group": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "study_id": {
                    "type": "string"
                },
                "target_votes_per_pair": {
                    "type": "integer"
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.LoginResponse": {
            "type": "object",
            "properties": {
                "admin": {
                    "$ref": "#/definitions/model.Admin"
                },
                "csrf_token": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "choice": {
                    "type": "string"
                },
                "confidence": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pair_presentation_id": {
                    "type": "string"
                },
                "participant_id": {
                    "type": "string"
                },
                "reason_codes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "replay_count": {
                    "type": "integer"
                },
                "response_time_ms": {
                    "type": "integer"
                }
            }
        },
        "model.StartSessionRequest": {
            "type": "object",
            "required": [
                "study_id"
            ],
            "properties": {
                "browser": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "experience": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "study_id": {
                    "type": "string"
                }
            }
        },
        "model.Study": {
            "type": "object",
            "properties": {
                "confidence_enabled": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "effect_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instructions_text": {
                    "type": "string"
                },
                "max_tasks_per_participant": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "reasons_enabled": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "tie_option_enabled": {
                    "type": "boolean"
                }
            }
        },
        "model.TaskPayload": {
            "type": "object",
            "properties": {
                "is_attention_check": {
                    "type": "boolean"
                },
                "is_practice": {
                    "type": "boolean"
                },
                "left": {
                    "$ref": "#/definitions/model.Video"
                },
                "presentation_id": {
                    "type": "string"
                },
                "right": {
                    "$ref": "#/definitions/model.Video"
                },
                "source_item_id": {
                    "type": "string"
                },
                "task_order": {
                    "type": "integer"
                }
            }
        },
        "model.TaskResponseRequest": {
            "type": "object",
            "required": [
                "choice"
            ],
            "properties": {
                "choice": {
                    "type": "string"
                },
                "confidence": {
                    "type": "integer"
                },
                "reason_codes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "replay_count": {
                    "type": "integer"
                },
                "response_time_ms": {
                    "type": "integer"
                }
            }
        },
        "model.UpdateStudyStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "model.Video": {
            "type": "object",
            "properties": {
                "checksum": {
                    "type": "string"
                },
                "codec": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "fps": {
                    "type": "number"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "method_type": {
                    "type": "string"
                },
                "presigned_url": {
                    "type": "string"
                },
                "s3_key": {
                    "type": "string"
                },
                "source_item_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.VideoStatus"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.VideoStatus": {
            "type": "string",
            "enum": [
                "active",
                "archived"
            ],
            "x-enum-varnames": [
                "VideoStatusActive",
                "VideoStatusArchived"
            ]
        },
        "service.AnalyticsOverview": {
            "type": "object",
            "properties": {
                "effects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.EffectAnalytics"
                    }
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.GroupAnalytics"
                    }
                },
                "tie_rate": {
                    "type": "number"
                },
                "total_participants": {
                    "type": "integer"
                },
                "total_responses": {
                    "type": "integer"
                }
            }
        },
        "service.EffectAnalytics": {
            "type": "object",
            "properties": {
                "effect_type": {
                    "type": "string"
                },
                "responses": {
                    "type": "integer"
                },
                "tie_rate": {
                    "type": "number"
                }
            }
        },
        "service.GroupAnalytics": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "responses": {
                    "type": "integer"
                },
                "tie_rate": {
                    "type": "number"
                }
            }
        },
        "service.QCReport": {
            "type": "object",
            "properties": {
                "fast_response_threshold_ms": {
                    "type": "integer"
                },
                "fast_responses": {
                    "type": "integer"
                },
                "straight_lining_profiles": {
                    "type": "integer"
                },
                "total_responses": {
                    "type": "integer"
                }
            }
        },
        "service.SessionCompleteResult": {
            "type": "object",
            "properties": {
                "completion_code": {
                    "type": "string"
                }
            }
        },
        "service.SessionStartMeta": {
            "type": "object",
            "properties": {
                "confidence_enabled": {
                    "type": "boolean"
                },
                "effect_type": {
                    "type": "string"
                },
                "instructions_text": {
                    "type": "string"
                },
                "max_tasks_per_participant": {
                    "type": "integer"
                },
                "reasons_enabled": {
                    "type": "boolean"
                },
                "study_id": {
                    "type": "string"
                },
                "study_name": {
                    "type": "string"
                },
                "tie_option_enabled": {
                    "type": "boolean"
                }
            }
        },
        "service.SessionStartResult": {
            "type": "object",
            "properties": {
                "assigned": {
                    "type": "integer"
                },
                "first_task": {
                    "$ref": "#/definitions/model.TaskPayload"
                },
                "meta": {
                    "$ref": "#/definitions/service.SessionStartMeta"
                },
                "session_token": {
                    "type": "string"
                }
            }
        },
        "service.StudyAnalytics": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.GroupAnalytics"
                    }
                },
                "left_win_rate": {
                    "type": "number"
                },
                "left_wins": {
                    "type": "integer"
                },
                "right_win_rate": {
                    "type": "number"
                },
                "right_wins": {
                    "type": "integer"
                },
                "study_id": {
                    "type": "string"
                },
                "tie_count": {
                    "type": "integer"
                },
                "tie_rate": {
                    "type": "number"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "CSRFToken": {
            "type": "apiKey",
            "name": "X-CSRF-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Video Comparison Service API",
	Description:      "Controlled pairwise video comparison platform for flooding/explosion research.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
